### ISSUE TITLE
Formación google maps y geolocalización

### ISSUE THREAD

**Issue by JoRoPi** [JdA-GestionDelTransporte/viajabus#1]
Instruir al Servicio cómo obtener desde google maps las coordenadas de geolocalización de una parada y viceversa.

**Comment by MJLuna** [comment]
Pedida , pendiente de que me den fecha

**Comment by JoRoPi** [comment]
El 2018-02-12 @MJLuna envía por correo el documento "Utilidades para tomar georeferencia.doc"
Basado en ese documento monto la página wiki [Utilidades para georeferenciar paradas](/JdA-GestionDelTransporte/viajabus/wiki/Utilidades-para-georeferenciar-paradas)
